name: Linting and testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build C++ implementations
        run: |
          mkdir knpy/build
          cd knpy/build
          cmake ..
          make
          make install
      - name: Upload built braid_cpp_impl module
        uses: actions/upload-artifact@v4
        with:
          name: Built braid_cpp_impl module
          path: knpy/braid_cpp_impl.*.so
      - name: Upload braid_cpp_impl stub
        uses: actions/upload-artifact@v4
        with:
          name: braid_cpp_impl stub
          path: knpy/braid_cpp_impl.pyi
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pylint-pytest
      - name: Lint with Pylint 
        run: |
          (cd knpy && pylint -v --disable fixme *.py)
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Test with pytest
        run: |
          PYTHONPATH=. pytest -v tests
